const data = [
  "Quasar luminosity redshift in the spiral arm.",
  "Nebula accretion disk event horizon pulsar.",
  "The geosynchronous transit passed the white dwarf zenith.",
  "Dark matter elliptical void et cosmic ray.",
  "Supernova remnants in the Kuiper Belt aphelion.",
  "Perigee syzygy during the solstice opposition.",
  "Exoplanet conjunction with a red giant magnetar.",
  "The meteoroid reached its nadir near the Oort Cloud.",
  "Singularity parallax of the neutron star bolide.",
  "Galactic perihelion through the celestial void.",
  "Elliptical orbit beyond the comet's apogee.",
  "Dark energy redshift observed in the protostar.",
  "Pulsar emissions from the transient quasar nebula.",
  "The bolide eclipse crossed the zenith at perihelion.",
  "Accretion disk of the solitary black hole singularity.",
  "Cosmic ray flux during the geosynchronous syzygy.",
  "White dwarf opposition to the spiral galaxy's core.",
  "Meteoroid stream from the distant Oort Cloud.",
  "Red giant luminosity fading past the event horizon.",
  "Kuiper Belt object in transit near aphelion.",
  "Neutron star pulsar et dark matter halo.",
  "The zenith nadir alignment during celestial equinox.",
  "Exoplanet discovered in the habitable conjunction.",
  "Supernova remnant energized the interstellar nebula.",
  "Parsec measurement of the blueshift quasar.",
  "Elliptical void between spiral arms.",
  "Magnetar flare detected at orbital perigee.",
  "Comet tail illuminated by the white dwarf.",
  "Galactic solstice and the cosmic ray background.",
  "The protostar's accretion disk reached singularity.",
  "Geosynchronous orbit above the elliptical apogee.",
  "Dark energy expansion beyond the local supernova.",
  "Redshift survey of the pulsar nebula.",
  "Bolide entered at zenith over the celestial sphere.",
  "Neutron star conjunction with a red giant.",
  "Oort Cloud perturbation by a passing magnetar.",
  "Event horizon of the supermassive black hole.",
  "Transit method confirmed the exoplanet's existence.",
  "Cosmic void measured in parsecs and lightyears.",
  "Syzygy of the quasar, pulsar, and red giant.",
  "Kuiper Belt debris into the inner solar system.",
  "Elliptical galaxy dominated by dark matter.",
  "The perihelion passage of the hyperbolic comet.",
  "Accretion disk luminosity rivaled the host galaxy.",
  "Geosynchronous satellite observed the solar zenith.",
  "White dwarf cooling into a black dwarf theoretical.",
  "Meteoroid shower originating from asteroid opposition.",
  "Protostar collapse triggered by a nearby supernova.",
  "Nebula filaments glow from the pulsar's energy.",
  "The grand conjunction approached its celestial nadir.",
];
export default data;
